### ISSUE TITLE
Rework the Color System

### ISSUE THREAD

**Issue by dillonschultz93** [dillonschultz93/quieto#37]
## Description
Rework the color system to be more uniform. 

## Tasks

- [ ] Rework the core color palette
- [ ] Limit the brand palette
- [ ] Rework the semantic palettes.
